# Generated by Django 3.1 on 2020-08-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_by', models.CharField(max_length=50)),
                ('assigned_to', models.CharField(choices=[('KKrysa', 'KKrysa'), ('KMyszkowski', 'KMyszkowski')], default='KKrysa', max_length=15)),
                ('description', models.TextField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(choices=[('Wysoki', 'Wysoki'), ('Normalny', 'Normalny'), ('Niski', 'Niski')], default='Normalny', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Nierozpoczęte', 'Nierozpoczęte'), ('W toku', 'W toku'), ('Zakończone', 'Zakończone'), ('Odroczone', 'Ddroczone')], default='Nierozpoczęte', max_length=200, null=True)),
            ],
        ),
    ]
