# Generated by Django 3.1 on 2020-08-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Wysoki'), ('2', 'Normalny'), ('3', 'Niski')], default='Normalny', max_length=10),
        ),
    ]
