# Generated by Django 3.1 on 2020-08-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200816_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Wysoki', '1'), ('Normalny', '2'), ('Niski', '3')], default='Normalny', max_length=10),
        ),
    ]
