# Generated by Django 3.1 on 2020-08-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200816_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Wysoki', '1 - Wysoki'), ('Normalny', '2 - Normalny'), ('Niski', '3 - Niski')], default='Normalny', max_length=10),
        ),
    ]
